### ISSUE TITLE
桌面端用户管理页面内容为空

### ISSUE THREAD

**Issue by MamaShip** [laipz8200/YobotWebInterface#3]
我使用一键脚本安装时，选择的版本是："2. 为yobot[v3.6.4-rc.2]安装"
而我的yobot实际版本是 yobot[v3.6.4]源码版 （yobot仓库Aug 13, 2020 的master版本：https://github.com/pcrbot/yobot/commit/270f4a63bf0f3c79a9a3453a66a756d4eff0fad1 ）

安装后其他方面使用正常，移动端的用户管理页面也正常显示。
但桌面端显示为空：
<img width="553" alt="屏幕快照 2020-09-01 10 47 05" src="https://user-images.githubusercontent.com/7104870/91789132-90d28800-ec40-11ea-80a8-4cdb948e148f.png">

**Comment by laipz8200** [comment]
移动端正常则桌面端应该没有问题，若以前在桌面端使用过yobot，更换主题后强制刷新清除浏览器缓存即可恢复正常。

若清除缓存后仍显示异常，请打开浏览器控制台并将错误信息截图反馈，感谢。

**Comment by laipz8200** [comment]
发现最新版yobot对个人信息页接口做了改动，暂不确定改动是否会导致项目显示出错，期待您的反馈

**Comment by laipz8200** [comment]
经测试最新版yobot使用无异常，应该是需要清除缓存。

如果有问题请再次反馈。

**Comment by MamaShip** [comment]
清除缓存后问题解决。多谢解答！
